/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/signup'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/signup'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/signup'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
  }
}

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
