/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForLandlordsRouteImport } from './routes/for-landlords'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardLandlordRouteImport } from './routes/dashboard.landlord'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLandlordsRoute = ForLandlordsRouteImport.update({
  id: '/for-landlords',
  path: '/for-landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandlordRoute = DashboardLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/landlord': typeof DashboardLandlordRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-agents'
    | '/for-landlords'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/signup'
    | '/terms'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
    | '/listings/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/for-agents'
    | '/for-landlords'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/signup'
    | '/terms'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
    | '/listings/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-agents'
    | '/for-landlords'
    | '/how-it-works'
    | '/listings'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/safety'
    | '/signup'
    | '/terms'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
    | '/listings/$id'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForLandlordsRoute: typeof ForLandlordsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-landlords': {
      id: '/for-landlords'
      path: '/for-landlords'
      fullPath: '/for-landlords'
      preLoaderRoute: typeof ForLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landlord': {
      id: '/dashboard/landlord'
      path: '/landlord'
      fullPath: '/dashboard/landlord'
      preLoaderRoute: typeof DashboardLandlordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardLandlordRoute: typeof DashboardLandlordRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardLandlordRoute: DashboardLandlordRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForLandlordsRoute: ForLandlordsRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
